dist: trusty

language: php

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+$/
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
  allow_failures:
    - php: 7.4snapshot

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls
